onboarding = false

[theme]
name = "dracula"
auto_switch = false

[keys]
prefix = "ctrl+q"

[[keys.command]]
key = "prefix+alt+g"
type = "popup"
command = "lazygit"
width = "90%"
height = "90%"

[ui.toast]
delivery = "terminal"

[ui]
show_agent_labels_on_pane_borders = true
